thirteenProject/Login_app/urls.py
from django.urls import path
from Login_app import views

app_name = "Login_app"

urlpatterns = [
    path('', views.index, name="index"),
    path('register/', views.register, name="register"),
    path('login/', views.login_page, name="login"),
    path('user_login/', views.user_login, name="user_login"),
    path('logout/', views.user_logout, name="logout")
]

thirteenProject/thirteenProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Login_app.urls'))
]


if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    

thirteenProject/Login_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class userInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    facebook_id = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to="profile_pics", blank=True)
    
    def __str__(self):
        return self.user.username
    

thirteenProject/Login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from Login_app import models


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password')
    
class UserInfoForm(forms.ModelForm):
    class Meta:
        model = models.userInfo
        fields = ('facebook_id', 'profile_pic')

thirteenProject/Login_app/views.py
from django.shortcuts import render
from Login_app import models, forms
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User

# Create your views here.
def index(request):
    data={}
    if request.user.is_authenticated:
        current_user = request.user
        user_id = current_user.id
        user_basic_info = User.objects.get(pk=user_id)
        user_more_info = models.userInfo.objects.get(user__pk=user_id)
        data={
            'title':'Index Page',
            'user_basic_info': user_basic_info,
            'user_more_info': user_more_info
        }
    return render(request, 'Login_app/index.html', data)

def register(request):
    registered = False
    if request.method == "POST":
        user_form = forms.UserForm(data=request.POST)
        user_info_form = forms.UserInfoForm(data=request.POST)
        if user_form.is_valid() and user_info_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            
            user_info = user_info_form.save(commit=False)
            user_info.user = user
            if 'profile_pic' in request.FILES:
                user_info.profile_pic = request.FILES['profile_pic']
            user_info.save()

            registered = True
                
    else:
        user_form = forms.UserForm()
        user_info_form = forms.UserInfoForm()
        
    data = {
        'title':'Register Page',
        'user_form': user_form,
        'user_info_form': user_info_form,
        'registered': registered
    }
    return render(request, 'Login_app/register.html', data)

def login_page(request):
    data = {
        'title':'Login Page'
    }
    return render(request, 'Login_app/login.html', data)

def user_login(request):
    data={
        'title': 'Login Page'
    }
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(username=username, password=password)
        
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('Login_app:index'))
            else:
                return HttpResponse("Account is not Active!!!")
        else:
            return HttpResponse("Login Details Are Wrong!!!")
    
    else:
        return render(request, 'Login_app/login.html', data)

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('Login_app:index'))

thirteenProject/Login_app/templates/Login_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>{{title}}</title>
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url "Login_app:index" %}">Home</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url "Login_app:logout" %}">Logout</a></li>
            {% else %}
            <li><a href="{% url "Login_app:register" %}">Register</a></li>
            <li><a href="{% url "Login_app:login" %}">Login</a></li>
            {% endif %}
        </ul>
    </nav>
    {% block body %}
    
    {% endblock body %}
</body>
</html>

thirteenProject/Login_app/templates/Login_app/index.html
{% extends 'Login_app/base.html' %}
{% block body %}
<h1>Index Page: </h1>
{% if user.is_authenticated %}
<p>Hi, {{user_basic_info.username}}</p>
<p>Your email is, {{user_basic_info.email}}</p>
<p>Your Facebook Profile Link: <a href="{{user_more_info.facebook_id}}" target=blank>Facebook Profile</a></p>
<p>Your Profile Pic:</p>
<img src="/media/{{user_more_info.profile_pic}}" width=200px alt="">
{% else %}
<h1>Please Login First!!!</h1>
{% endif %}
{% endblock body %}

thirteenProject/Login_app/templates/Login_app/login.html
{% extends 'Login_app/base.html' %}

{% block body %}
<h1>Login Page:</h1>
<form action="{% url "Login_app:user_login" %}" method="POST">
    <label for="username">User Name: </label><br>
    <input type="text" name="username" placeholder="Enter Username..." required><br><br>
    <label for="password">Password: </label><br>
    <input type="password" name="password" required placeholder="Enter Password......"><br><br>

    {% csrf_token %}

    <input type="submit" value="Login" name="submit">
</form>
{% endblock body %}

thirteenProject/Login_app/templates/Login_app/register.html
{% extends 'Login_app/base.html' %}

{% block body %}
<h1>Register Form:</h1>
{% if registered %}
<div><h1>Congrats Register Success</h1></div>
{% else %}
<form enctype="multipart/form-data" method="POST">
    {{user_form.as_p}}
    {{user_info_form.as_p}}
    {% csrf_token %}
    <input type="submit" value="Submit" name="submit">
</form>
{% endif %}
{% endblock body %}